### ISSUE TITLE
Bootstrap the project

### ISSUE THREAD

**Issue by SandaruLJ** [SandaruLJ/schoolr-api#1]
Start the project with a well-planned structure. This will help with scalability in the future.
### Subtasks
- [x] Declare project metadata
- [x] Implement a way to specify app configurations
- [x] Configure connection to the database
- [x] Configure logging
- [x] Configure testing
